---
driver:
  name: vagrant

provisioner:
  name: chef_solo
  require_chef_omnibus: 11.16

platforms:
  - name: centos-7.1
    driver:
      network:
      - ["forwarded_port", {guest: 4444, host: 4444}]

  - name: ubuntu-14.04
    driver:
      network:
      - ["forwarded_port", {guest: 4444, host: 4445}]

  - name: windows-2012r2
    driver:
      box: dhoer/windows-2012r2
      network:
      - ["forwarded_port", {guest: 4444, host: 4446}]
    attributes:

suites:
  - name: selenium_test
    run_list:
      - recipe[selenium_test::package]
      - recipe[selenium_test::hub]
      - recipe[selenium_test::node]
    attributes:
      mozilla_firefox:
        32bit_only: true
